fury-gl/fury

.codecov.yml
.coveragerc
ISSUE_TEMPLATE.md
README.rst
fury/window.py

Some examples do not work on `Dipy` because `fury.window.colors` do not exist.
The aim of this PR is to fix this small issue.
I use this opportunity to:
- Update readme
- Add codecov.yml
- Add coveragerc
- Add Issue template

Add vtk.util.colors for backward compability

---

docs/examples/viz_surfaces.py
fury/io.py
fury/tests/test_io.py

The goal of this PR is to fix the Travis issue [here](https://travis-ci.org/fury-gl/fury/jobs/467619790#L3381)
I use this opportunity to move the `io` module from DIPY.

[Fix] viz_surface

---

fury/window.py

Fix elementwise comparison deprecation warning:
```
/Users/travis/build/fury-gl/fury/fury/window.py:942: DeprecationWarning:
elementwise == comparison failed; this will raise an error in the
future.
```
The warning is thrown when the image and the color arrays differ in the
alpha channel being present/absent.
Fixes #37.

BUG: Fix elementwise comparison deprecation warning.

---

fury/actor.py

The actor created in `peak_slicer` was not having its properties
enforced because the `PeakSlicerActor` instance was not explicitly
setting its `vtk::Property` properties. These properties were being set
in the actor of the `self.line` object, but needed to be set for the
`PeakSlicerActor` class itself.
Fixes #22.

BUG: Fix `peaks_slicer` actor properties not being enforced.

---

fury/actor.py
fury/tests/test_actors.py

Fix `TensorSlicerActor` actor opacity property not being enforced.
The method `tensor_slicer` returns an instance of a `TensorSlicerActor`
actor, and receives, among others the `opacity` that needs to be applied
to the actor as a parameter. However, the parameter was being passed to
the `_tensor_slicer_mapper` method, which returns a mapper, and thus was
not effectively using the `opacity` property.
Now the `opacity` parameter is no longer passed to the
`_tensor_slicer_mapper` and it is set as a `vtk::Property` to the
`TensorSlicerActor` instance.
The corresponding actor test is modified so that the `opacity` property
is effectively exercised.

BUG: Fix `TensorSlicerActor` actor opacity property not being enforced.

---

fury/__init__.py

[Fix] add filterwarnings

---

fury/__init__.py
fury/tests/test_optpkg.py

This PR is adding an utility function. The result of `get_info` is:
```
In [1]: from fury import get_info
In [2]: get_info()
Out[2]: 
{'fury_version': '0.1.4.post133+gc1d89c5',
'pkg_path': 'C:\\Users\\skoudoro\\Devel\\fury\\fury',
'commit_hash': 'c1d89c58bafd5b60bea0ba545ece0d89d0d93bb0',
'sys_version': '3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)]',
'sys_executable': 'C:\\Users\\skoudoro\\AppData\\Local\\Continuum\\Anaconda3\\envs\\fury-dev-3\\python.exe',
'sys_platform': 'win32',
'np_version': '1.15.4',
'scipy_version': '1.1.0',
'vtk_version': 'vtk version 8.1.1',
'matplotlib_version': '3.0.2',
'dipy_version': '0.16.0dev'}
In [3]: 
```

[NF] Add get_info function

---

fury/window.py

`Colors`module from VTK is back

backward compatibilities

---

fury/actor.py
fury/tests/test_actors.py

This adds an option to color each point on each ODF by the direction on the sphere, so similarly oriented peaks have the same color. This is a common, and in my opinion extremely helpful, way to visualize multiple ODFs. 
Similar to how the same functionality is implemented in `peak_slicer`, this option is implemented by setting `colormap=None`. Currently, this throws an error if `colormap=None` and `global_cm=True`, but these are already sort of conflicting commands. 
Here are comparative visualizations, using the CSD example in the DIPY gallery: (http://nipy.org/dipy/examples_built/reconst_csd.html#example-reconst-csd)
`colormap='Plasma'`
`colormap='None'`

Directional color odfs

---

fury/actor.py
fury/tests/test_actors.py

This is a simple PR to allow a list of str as a grid captions for `actor.grid` and `ui.GridUI`.
Both can be mixed. It is convenient.

Allow Str for Grid Caption

---

.travis.yml
appveyor.yml
ci/appveyor/install.ps1
ci/appveyor/run_with_env.cmd
ci/appveyor/script.ps1
ci/travis/install.sh
fury/tests/test_actors.py
fury/tests/test_interactor.py
fury/tests/test_ui.py
fury/tests/test_utils.py
fury/tests/test_window.py
fury/ui.py

Add Appveyor for windows unittest. It should be merged after #72

Add appveyor

---

fury/actor.py
fury/tests/test_actors.py

As suggested by @agramfort this PR adds a function `cone()` that creates cone glyphs given `centers`, `resolutions` or `heights` with some basic testing in `fury/tests/test_actors.py::test_cones`.

Add cones as glyphs

---

docs/tutorials/viz_ui.py
requirements/default.txt

Also, adds six as a requirement.
See: https://github.com/fury-gl/fury/blob/master/fury/ui.py#L8

Fixes a typo in the viz_ui tutorial.

---

fury/tests/test_utils.py
fury/utils.py

This should fix a small issue with the code below:
```
from fury import actor, window, layout
c = actor.Container(layout=layout.GridLayout())
c.add(actor.axes(), actor.axes())
s=window.Scene()
s.add(c)
window.show(s)
```
I use the opportunity to fix some pep8 and add a test

[Fix] layout with small cells

---

docs/examples/viz_advanced.py
docs/examples/viz_roi_contour.py
docs/source/ext/apigen.py
docs/source/ext/build_modref_templates.py
fury/data/fetcher.py
fury/io.py
fury/tests/test_actors.py
fury/tests/test_interactor.py
fury/tests/test_ui.py
fury/tests/test_window.py
requirements/test.txt

This PR removes `nose` package dependency by replacing `skipif` function.
I use the opportunity to solve some pep8 issue

Remove nose dependency

---

README.rst
docs/examples/viz_advanced.py
docs/source/conf.py

Quick PR to fix doc generation and specifically: 
this error via [this workaround](https://github.com/sphinx-doc/sphinx/issues/6695#issuecomment-530009784): 
```
Exception occurred:
File "/home/travis/envs/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py", line 726, in process_generate_options
for genfile in genfiles]
```
and this error:
```
Warning, treated as error:
/Users/koudoro/Software/fury/docs/examples/viz_advanced.py failed to execute correctly: Traceback (most recent call last):
File "/Users/koudoro/miniconda3/envs/fury-env-37/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 430, in _memory_usage
out = func()
File "/Users/koudoro/miniconda3/envs/fury-env-37/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 415, in …
```

[Fix] doc generation

---

fury/actor.py
fury/primitive.py
fury/tests/test_actors.py
fury/tests/test_primitive.py
fury/tests/test_transform.py
fury/transform.py
fury/utils.py

Adding the superquadrics actor and primitive. Below a small example to use it
```
from fury import window, actor
centers = np.random.rand(3, 3) * 10
directions = np.random.rand(3, 3)
colors = np.array([[255, 0, 0], [0, 255, 0], [0, 0, 255]])
scale = np.random.rand(5)
roundness = np.array([[1, 1], [1, 2], [2, 1]])
sq_actor = actor.superquadric(centers, roundness=roundness,
directions=directions,
colors=colors, scale=scale)
scene.add(sq_actor)
window.show(scene)
```

Add Superquadric primitives and actors

---

fury/io.py

Fix docstrings for methods `io:load_image` and `io:save_image`:
- Remove non-existing parameter doc from `io:load_image`.
- Add the `optional` keyword to optional parameters.

DOC: Fix `io:load_image` and `io:save_image` docstrings

---

fury/tests/test_ui.py
fury/ui.py

Referencing #15 and #166 , my objective is to prevent text overflow in ListBox2D. As issue #15 is similar to #166 I am referencing both the issues within this Pull Request.
* Added Fix to prevent text-overflow in ListBox2D by replacing the **end of the string** exceeding the width of the item slot with `...`
```python
import fury.ui as ui
import fury.window as window
values = ['abcdefghijklmnopqrstuvwxyz', 'ahdfjkhkashdfjkhdskfhiweuroqweqr', 'akdiuhdaiufhasdfusdffsdfusdyf', 'Soham']
listbox = ui.ListBox2D(values=values, size=(300, 300))
sm=window.ShowManager(size=(600,600))
sm.scene.add(listbox)
sm.start()
```
Thank You. :heart:

Fixing Text Overflow of ListBox2D

---

fury/actor.py

Improve the `fury.actor` documentation:
- Fix the `actor.line` method `lookup_colormap` parameter type:
```
lookup_colormap : bool, optional
```
to
```
lookup_colormap : vtkLookupTable, optional
```
- Add the `optional` keyword for optional arguments in various methods in
`fury.actor`.

DOC: Fix `actor.line` parameter type and add `optional` keyword

---

docs/tutorials/03_shaders/viz_shader.py
fury/tests/test_actors.py

The superquadrics test was failing often due to the scale randomness. Indeed, some really small actors were not detected and some huge actors were taking too much space. 
Now, the test is a bit more deterministic.

[FIX] Update superquadrics test

---

fury/tests/test_utils.py
fury/utils.py

Closing previous PR, all changes made and redone.

Utils test and winding order algorithm 

---

docs/tutorials/02_advanced_ui/viz_ui.py
fury/tests/test_ui.py
fury/ui.py

* Adding a vertical layout for `RangeSlider`.
```python
from fury import ui, window
range_slider_hor = ui.RangeSlider(
line_width=8, handle_side=25, range_slider_center=(200, 500),
value_slider_center=(200, 400), length=250, min_value=0,
max_value=10, font_size=18, range_precision=2, value_precision=4,
shape="square")
range_slider_ver = ui.RangeSlider(
line_width=8, handle_side=25, range_slider_center=(475, 450),
value_slider_center=(375, 450), length=250, min_value=0,
max_value=10, font_size=18, range_precision=2, value_precision=4,
orientation="vertical", shape="square")
current_size = (800, 800)
show_manager = window.ShowManager(size=current_size, title="Range Sliders Example")
show_manager.scene.add(range_slider_hor)
show_manager.scene.add(range_slider_ver)
show_manager.start()
```

Vertical Layout for RangeSlider

---

fury/window.py

The window.SetWindowName() should always be called after the window.Render(), as mentioned in the VTK documentation.

Namanb009 windowtitlefix

---

requirements/default.txt

Referencing #219 , bumping minimum scipy version requirement from `0.9` to `1.2.0` for fixing `scipy.spatial.transform` module not found error.

bumping scipy version to 1.2.0

---

fury/actor.py
fury/tests/test_actors.py

In reference to issue #77 
* Takes `Labeled Array`, `affine`, `colors` and `opacity` as arguments for individual surfaces.
* Extracts unique _Regions of Interest_ from the labeled array.
* Generates unique **ROI** surfaces and returns them in a vtkAssembly instance in order of their label IDs.

Added contour_from_label method

---

README.rst
fury/actor.py
fury/utils.py

Due to backward compatibilities, I revert a previous change. By default, the streamlines will be colored with a standard orientation colormap instead of no color.
fix #135

[Fix] update streamlines default color

---

fury/colormap.py
fury/tests/test_colormap.py

Here is a cleaner PR for #216 
This function will allow users to use hexadecimal color throughout FURY instead of rgb.
Type: Enhancement
Improves User usability.

Function to use Hexadecimal color code in Colormap

---

fury/actor.py
fury/tests/test_actors.py
fury/tests/test_window.py
fury/utils.py

This PR update some FURY functions due to some changes in VTK 9. The main change is better management of vtkCellArray.
Wheels available on Pypi only for Windows and macOS. Concerning Linux, you have to download the wheel on VTK website. (https://discourse.vtk.org/t/vtk-9-wheels-on-pypi/3340/4)
VTK Releases Announcement :  https://blog.kitware.com/vtk-9-0-0-available-for-download/
VTK API changes from 8.2 to 9.0: https://vtk.org/Wiki/VTK/API_Changes_8_2_0_to_9_0_0
VTK 9 build process : https://vtk.org/doc/nightly/html/md__home_kitware_dashboards_buildbot_vtk_nightly-master-ike-linux-shared-release_doc_nightly_osm749dd663df9981384f2598c108aac3b0.html

[FIX]  Compatibility with VTK 9

---

docs/tutorials/01_introductory/viz_picking.py
fury/pick.py
fury/tests/test_pick.py
fury/utils.py

This PR introduces a new class called ``PickingManager`` .
This class helps with getting information from actors in the 3D world. 
You can receive vertex indices, face indices, world coordinate positions and actor ids.
Also very importantly this class shows how to directly access and update the vertices and colors of objects. Have in mind that there could be many objects in one actor. 
@Nibba2018, @filipinascimento, @lenixlobo, @mlraglin, @nasimanousheh
This PR resolves issue https://github.com/fury-gl/fury/issues/228

Picking API and picking tutorial

---

fury/decorators.py
fury/deprecator.py
fury/tests/test_ui.py
fury/tests/test_window.py
fury/window.py
requirements/default.txt
setup.py

Based on @MarcCote PR in [my fork](https://github.com/skoudoro/fury/pull/4):
With this fix and the latest VTK' [release branch](https://gitlab.kitware.com/vtk/vtk/-/tree/release) (which includes the fix for the TimerEvents), all fury tests are green except for `fury/tests/test_window.py::test_order_transparent` :-/. 
Edit: this fixes https://github.com/fury-gl/fury/issues/253

Let VTK delete timers on exit.

---

fury/deprecator.py
fury/tests/test_deprecator.py

This PR adds a decorator to deprecate one or multiple parameters from a function.
```python
>>> from fury.deprecator import deprecated_params
>>> @deprecated_params('sig', 'sigma', '0.3')
...    def test(sigma):
...        return sigma
>>> test(2)
2
>>> test(sigma=2)
2
>>> test(sig=2)
/Users/koudoro/miniconda3/envs/fury-env-37/bin/ipython:1: ArgsDeprecationWarning: "sig" was deprecated
* deprecated from version: 1.0
* Use argument "sigma" instead.
2
>>> @deprecated_params(['a', 'b'], ['alpha', 'beta'], since=['0.2', 0.4], until=['0.7', '0.6'])
...    def test(alpha, beta):
...        return alpha, beta
>>> test(a=2, b=3)
/Users/koudoro/miniconda3/envs/fury-env-37/bin/ipython:5: ArgsDeprecationWarning: "a" was deprecated
* deprecated from version: 0.2
* Use argument "alpha" instead. …
```

[NF] Deprecated parameters

---

docs/examples/viz_advanced.py
fury/tests/test_ui.py
fury/ui.py

Working example of setting a BBox for a `vtkTextActor` using `vtkTextRepresentation` and `vtkTextWidget`:
```python
import vtk
renderer = vtk.vtkRenderer()
renderer.SetBackground(0.1, 0.2, 0.4)
render_window = vtk.vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(400, 400)
interactor = vtk.vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)
text_actor = vtk.vtkTextActor()
text_actor.SetInput("This is a test")
text_actor.GetTextProperty().SetColor((0, 1, 1))
text_representation = vtk.vtkTextRepresentation()
text_representation.GetPositionCoordinate().SetCoordinateSystemToDisplay()
text_representation.GetPosition2Coordinate().SetCoordinateSystemToDisplay()
text_representation.GetPositionCoordinate().SetValue(200, 200) …
```

Setting Bounding Box for TextBlock2D

---

docs/tutorials/01_introductory/viz_earth_coordinates.py
fury/data/fetcher.py

This PR includes a new tutorial for FURY, including a new function to convert longitude and latitude coordinates of any location on Earth to coordinates for a sphere actor on that exact location called ``latlong_coordinates``. This tutorial also demonstrates how to add several actors to a scene at once, as well as create some camera flyover movement in an animation.
The texture used for this tutorial is a new 16k resolution Earth texture, which was added to fetcher.py.
When the animation is run, it will fly over three different cities on Earth, each with their own text label to indicate the city, country, and its coordinates, as produced by ``latlong_coordinates``.

Adding new Earth coordinates tutorial

---

.mailmap
AUTHORS.rst
docs/source/ext/github_tools.py
docs/source/posts/2020/2020-07-20-release-announcement.rst
docs/source/release-history.rst
docs/source/release_notes/releasev0.6.0.rst
setup.py

Preparation for 0.6.0 release, targeting Monday, July 20th. 
September.

Release 0.6.0 preparation

---

fury/actor.py
fury/utils.py

This PR should fix #280, and a part of #269.  Colors array had different names in our codebase so I just normalize this point.

Standardize Colors array name 

---

fury/actor.py
fury/primitive.py
fury/tests/test_actors.py
fury/tests/test_primitive.py
fury/tests/test_utils.py
fury/tests/test_window.py
fury/utils.py
fury/window.py

The goal of this PR is to standardize colors across the API [0 -1]
fix #271
fix #242
fix #243 
supersede and fix #269
This PR should be merged after #282

Standardize colors across API

---

docs/tutorials/01_ui/viz_check_boxes.py
docs/tutorials/01_ui/viz_radio_buttons.py

This is the first part of the tutorial in reference to issue number #205.
This tutorial demonstrates the use of RadioButton UI, we can toggle the colors of the cube using the given options.

Added tutorial for RadioButton and CheckBox UI 

---

fury/__init__.py

This PR adds a utility function to switch ON or OFF the global warning window of VTK. By default, it is ON on the dev version and OFF for the release version. 
fix #270.

Disable VTK Warnings on release version 

---

.mailmap
AUTHORS.rst
docs/source/posts/2020/2020-06-07-week-2-lenix.rst
docs/source/posts/2020/2020-06-28-week-5-soham.rst
docs/source/posts/2020/2020-08-02-week-10-soham.rst
docs/source/posts/2020/2020-08-18-release-announcement.rst
docs/source/release-history.rst
docs/source/release_notes/releasev0.6.1.rst
docs/tutorials/02_ui/viz_radio_buttons.py
docs/tutorials/05_physics/README.rst
fury/deprecator.py

Preparation for 0.6.1 release, targeting Tuesday, August 18th. 
October.

Release 0.6.1 preparation 

---

docs/source/_templates/page.html
docs/source/community.rst

Fixes #313
The discord icon was not available in Font-Awesome v4.x. 
Had to use Font-Awesome v5.x CDN and changed the syntax according to the new version of FA.
I tried pulling the only brands.css, but it didn't worked well.

fixed discord icon bug in documentation

---

fury/actor.py
fury/window.py

This PR is due to some change on the alpha channel with VTK9.
The event on the actor is not called if we do not force the LUT to be RGB. This is a quick fix for DIPY Horizon but we need to go deeper in our custom interactor.
See the code below to reproduce the error:
```
from fury import actor, window
arr = np.random.rand(125).reshape((5, 5, 5)) * 255
def left_click_callback(obj, ev):
print('CALLBACK')
print(obj)
fig = actor.slicer(arr)
fig1 = fig.copy()
fig1.display(None, None, 0)
print(fig1.shape)
fig1.SetInterpolate(False)
fig1.AddObserver('UserEvent',
left_click_callback, 10000.0)
showm = window.ShowManager(scene, interactor_style='custom')
showm.initialize()
scene.add(fig1)
showm.start()
```

[FIX] Force LUT to be RGB

---

fury/primitive.py
fury/tests/test_primitive.py

Closes #318 
Referred to this [source](http://songho.ca/opengl/gl_cylinder.html) for generating vertices and triangles.
Formatted the `primitive.py` according to PEP 8.

Added cylinder primitive

---

pytest.ini

Context: #317 
The following warning:
`DeprecationWarning: Converting 'np.character' to a dtype is deprecated. The current result is 'np.dtype(np.str_)' which is not strictly correct. Note that 'np.character' is generally deprecated and 'S1' should be used.`
is generated when numpy arrays are converted to vtk arrays in `vtk.util.numpy_support.get_vtk_array_type`. This method is mainly used by the methods in `fury.utils` and `fury.actors`. This warning is generated when arrays contain character values in them, but while test I was not able to find any character values present in the array when the tests are run.
This warning is also the most recurring warning compared to the rest and also the only one in `fury.ui`. I created a file `pytest.ini` to ignore this particular warning and got the …

Fixing UI warnings

---

fury/tests/test_ui.py
fury/ui.py

Closes #308 
If we have to clip from left, we reverse the string before processing it and then reverse it again before returning it.

Add support for clipping side in clip_overflow_text

---

docs/source/ext/github_tools.py

Pass OAuth token through header

---

docs/Makefile
docs/README.md
docs/make.bat
docs/source/installation.rst

All is in the title. This PR allow the user to generate the documentation faster (without running the examples).
@Nibba2018, can you test it on Windows? it is ok on Linux and MacOsx

Add Option to generate the documentation without examples

---

fury/actor.py
fury/tests/test_actors.py

Fixes #335 
Earlier, 
Now, 
Earlier, opacity argument wasn't manipulating the opacity of point actors and sphere actors. That issue is resolved by this fix. Unit tests are included for the same.

Opacity bug fix for point and sphere actors

---

fury/actor.py
fury/tests/test_actors.py

Closes #310 
If enough primitives are not provided, we default to a torus. Another possible solution could be trying to broadcast the NumPy arrays before defaulting to a torus.

Fix the sdf bug by checking the arguments passed

---

fury/colormap.py

In the documentation of colormap.py, the documentation regarding the auto argument in the create_colormap function had minor errors as its function interpolate from [0,1] but Docs wrote it as [0,10].

Solving The Minor Documentation Error

---

docs/examples/viz_fiber_odf.py
fury/actor.py
fury/actors/odf_slicer.py
fury/colormap.py
fury/data/__init__.py
fury/data/fetcher.py
fury/tests/test_actors.py
fury/utils.py

Hi,
I did some refactoring of `actor.odf_slicer` with the objective to make it faster and less memory greedy.
Basically:
* I replaced `for` loops by `numpy` array operations;
* I added the option to supply ODFs in SH coefficients, when given a B matrix;
* I added a method to change the sphere used for visualization when using SH coefficients;
* I changed the `numpy` method called in `utils.set_polydata_triangle` for one that completes faster;
* I applied the affine transform to the grid as well as to the ODFs themselves, as suggested [here](https://github.com/fury-gl/fury/issues/10);
* I moved the class `OdfSlicerActor` to the new module `fury.actors.odf_slicer` to make some space in `fury.actor` module;
* I wrote tests.
If there is some ODF data available somewhere, I would gladly add an …

ENH: Refactor actor.odf_slicer for increased performances

---

README.md
fury/tests/test_utils.py
fury/utils.py

This PR assures that we update all array when we call `update_actor`

[fix]   Propagate update_actor

---

fury/actor.py

Earlier, `scales` was incorrectly initialised and `colors` was not initialised at all, as a result, example was not working. That's fixed now.

fixed the example for superquadric function

---

docs/examples/viz_brownian_motion.py

I made a small simulation of 4 particles exhitbiting brownian motion using FURY.
Preview- 
https://user-images.githubusercontent.com/65067354/109386815-6299e080-7923-11eb-8a83-ad081cca561f.mp4

added simulation for brownian motion

---

docs/source/ext/github_tools.py
fury/tests/test_actors.py
fury/tests/test_convert.py
fury/tests/test_utils.py
fury/window.py

This commit will hopefully close issues #317 and #355.
---
I did not create tests for layout.py since it looks like a helper in actors.py.
I could say the same about convert.py but even then, I tried creating basic tests.
If these files grow in future, they might need their own tests.
As for #355, it's a really simple check just before we fetch the url.
Thank you for your time!
I'd appreciate any feedback...

Resolve warnings #317 & and Fix Issue: #355

---

README.md

Some links in the readme redirect to wrong links so changing them to correct links:
Blogs refer to https://fury.gl/dev/blog but the working link is https://fury.gl/latest/blog.html
Similarly, More Installation Info refers to https://fury.gl/stable/installation.html but the working link is https://fury.gl/latest/installation.html
Thank You.

Updating Redirecting Issues in Readme

---

docs/examples/viz_network_animated.py

Removed  imported but unused vtk library in FURY Visualize Networks (Animated version) demo.

Removed unused library in FURY tutorial

---

.github/ISSUE_TEMPLATE/generic-issue-template.md

For the Operating System and Version Info on Line 21, the command `print`  didn't had the closing parenthesis, so adding that as without that it throws an error while executing.

Updating the Missing Parenthesis

---

docs/tutorials/01_introductory/viz_solar_system.py
fury/tests/test_utils.py
fury/utils.py

fixed warning in test_utils.py.
warning was: #317 
```
fury/tests/test_utils.py::test_trilinear_interp
fury/tests/test_utils.py::test_trilinear_interp
D:\fury-master\fury\tests\test_utils.py:133: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
x0 = x_indices.astype(np.integer)
fury/tests/test_utils.py::test_trilinear_interp
fury/tests/test_utils.py::test_trilinear_interp
D:\fury-master\fury\tests\test_utils.py:134: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not …
```

Fixed warnings in test_utils.py

---

fury/tests/test_layout.py

This PR adds tests for the layout module. This PR extends/modifies the PR opened by @jhalak27 ( #411 ).
Along with the tests a `get_default_cubes` method is also implemented that provides default parameter cube actors to test the grid with. The `GridLayout`  as well as the `Layout` classes are tested with these default cubes as it makes the visualization of the grid behavior easier.
Diagonal Grid
Square/Rect Grid

WIP: added tests for layout module

---

docs/examples/viz_play_video.py
fury/actor.py
fury/tests/test_actors.py
requirements/docs.txt

Render a video on an actor.
======================
This PR Consists of 2 parts:
- Function to change the texture of a vtkActor
- A demo file to visualize, rendering of a Video.
Fury actors didn't have a function to change the texture of an already textured vtkActor. There was a requirement for this function while rendering a video on an Actor. The function accepts an actor object and an image. The image gets mapped in the same mapper as configured while creating the actor.
To test the function an actor is created with a black texture which is changed and tested with the new texture.
The goal of this demo is to show how to visualize a video on a Plane, which can be extended to potentially all shapes
This class wraps OpenCV VideoCapture with the required functionalities 
This class creates …

Render a video on an actor.

---

fury/io.py
fury/tests/test_io.py
fury/ui.py

This adds support for fetching the image from a URL. The image is stored in the directory temporarily until the image has been processed, then it is removed from the directory. I'll try to look at other approaches that may be more flexible than this in the meantime and update this if necessary.

added support for URL image in ImageContainer2D

---

docs/examples/viz_nested_block_model.py

Hi!
I made an example of how to integrate the graph-tool with FURY

added an example about graph-tool  and nested stochastic block model

---

fury/actor.py

Hi! 
This is a fix for issue #429 .
@SunTzunami and I hopped on a call and fixed it together.
I think, this is exactly how It should look...
I've also changed the documentation to include the range of the Individual color values. 
In case someone else is confused due to this.

Surface actor colormap fix

---

.mailmap
docs/source/posts/2021/2021-08-03-release-announcement.rst
docs/source/release-history.rst
docs/source/release_notes/releasev0.7.1.rst

Preparation for 0.7.1 release, targeting, August 3rd. 
September.

Release 0.7.1 preparation

---

docs/examples/viz_fine_tuning_gl_context.py
fury/shaders/__init__.py
fury/shaders/base.py
fury/tests/test_window.py
fury/utils.py
fury/window.py

This it's related with  #428
Hi @Garyfallidis and @skoudoro. I didn't finish yet, but I'm sending the pull-request to get feedbacks or suggestions.
I've created a function inside of shaders/base.py (shader_apply_effects) in order to make the control of the opengl_state more  simple.
```python
id_observer = shader_apply_effects(
showm, actorAdd,
effect=window.gl_set_additive_blending)
###############################################################################
id_observer =  shader_apply_effects(
showm, actorNoDepthTest2,
effects=[
window.gl_reset_blend, window.gl_disable_blend,
window.gl_disable_depth])
```

Fine-tuning of the OpenGL state

---

fury/actor.py
fury/primitive.py
fury/tests/test_actors.py
fury/tests/test_primitive.py
fury/tests/test_scene.py

I made a primitive for pentagonal prism and created an actor for the same.
Added tests for actor and primitive too.
Preview:

Add primitive and actor for pentagonal prism with test

---

fury/ui/elements.py

This PR fixes [DIPY #2441](https://github.com/dipy/dipy/issues/2441) and similar problems with the slider.

Fix disk position outside the slider line

---

fury/io.py
fury/tests/test_io.py
fury/window.py

This PR fixes the issue reported in https://github.com/fury-gl/fury/issues/467
Basically, we were not flipping the images correctly in ``save_image`` and ``load_image``. ``save_image`` was called by ``snapshot``.

Snapshot flipping bug fix

---

fury/actor.py
fury/tests/test_actors.py

This is a follow-up of [this comment](https://github.com/fury-gl/fury/pull/489#discussion_r719525377) from #489.
The goal is to:
- rename `label(...)` to `vector_text(...)`
- deprecate `label` and warn the users of the change

Deprecate and rename label to vector_text

---

fury/actor.py
fury/tests/test_utils.py
fury/utils.py

This PR should fix #526. Text justification of vtkTextActor3D is working fine so we remove our patch and create a utility function for later use just in case we need it again.

[FIX] remove update_user_matrix from text3d

---

fury/actors/peak.py
fury/lib.py
fury/material.py
fury/shaders/base.py
fury/tests/test_actors.py
fury/tests/test_deprecator.py
fury/tests/test_material.py
fury/utils.py

Currently, we are depending only on VTK 9.1.0 so this flag is not necessary anymore.

Remove VTK_9_PLUS flag

---

docs/upload_to_gh-pages.py
setup.cfg
setup.py

We were using setuptools in half so this PR goal is to migrate completely to setuptools

Improve setuptools

---

.github/workflows/test.yml
docs/tutorials/01_introductory/viz_picking.py

Our GHA Ci seems to fail on Ubuntu because they do not find a deb package. 
by doing a system update, it should refresh the package list and fix the right one.

Force mesa update

---

fury/io.py
fury/tests/test_io.py

Currently, io.load_cubemap_texture() checks for existence of the files
it is asked to open, and raises FileNotFoundError if needed. Added
checks to io.load_polydata() and io.load_image().

Check to see if file exists before opening

---

fury/window.py

This PR allows ``fury.window.record`` to go offscreen as it should, and not create any windows while saving images. 
This is resolving the memory issue when repeatedly calling record. And the fact that you see a black window for a few seconds.
See relevant issues here:
https://github.com/fury-gl/fury/issues/548
https://github.com/fury-gl/fury/issues/196
```
from fury import window, actor
t = np.linspace(-10, 10, 100)
bundle = []
for i in np.linspace(3, 5, 1000):
pts = np.vstack((np.cos(2 * t/np.pi), np.zeros(t.shape) + i*10, t )).T
bundle.append(pts)
ren = window.Scene()
for time in range(200):#len(plot_params["rod0"]["time"])):
ren.clear()
bundle_actor = actor.streamtube(bundle, window.colors.red, linewidth=0.01)
ren.add(bundle_actor) …
```

Record should not make the window appear

---

requirements/docs.txt

I was unable to build the docs, and I found that `requirements/docs.txt` wasn't updated when the theme was changed. Replaced `sphinx_rtd_theme` with `pydata-sphinx-theme`.

Replace theme in requirements/docs.txt

---

fury/primitive.py

Currently, 2 of the faces returned by `primitive.prim_tetrahedron()` have the vertices in incorrect order. This leads to incorrect normals being calculated, and the two faces in question appear invisible from the outside.
Current version: Note the missing faces!
Fixed version: All faces are now visible from the outside.
Minimal reproducible example:
```python
from fury import utils, window, primitive
v, f = primitive.prim_tetrahedron()
a = utils.get_actor_from_primitive(v, f)
scene.add(a)
window.show(scene)
```

Fix vertex order in prim_tetrahedron

---

docs/source/conf.py

Fixed static path as the previous path restricted static content to the css folder only

Fixed the static path in configuration file for docs

---

fury/actor.py
fury/lib.py
fury/primitive.py
fury/tests/test_actors.py
fury/tests/test_primitive.py
fury/utils.py

Fixed the issue of the rotation matrix that I mentioned in issue #554. 
What I did was assume all primitives have a normal vector pointing in X-axis (1, 0, 0), then the matrix to align this normal vector of the primitives to the direction vector specified.
I tested the matrix on my arrow using **repeat_primitive** and **repeat_source** and got a match.
```
from fury import window, actor
centers = np.zeros([3, 3])
dirs = np.identity(3)
colors = np.identity(3)
scales = np.array([2.1, 2.6, 2.5])
rpactor = actor.arrow(centers, dirs, colors=colors, scales=1.5)
rsactor = actor.arrow(centers, dirs, colors=colors, repeat_primitive=False)
cen2 = np.random.rand(5, 3)
dir2 = np.random.rand(5, 3)
cols2 = np.random.rand(5, 3)
rpactor2 = actor.arrow(cen2, dir2, …
```

Fixed the rotation matrix in repeat_primitive.

---

docs/tutorials/01_introductory/viz_solar_system.py

Implemented the ability to pause and resume the animation with the use of buttons.

Added play/pause buttons

---

fury/actor.py
fury/actors/peak.py
fury/material.py
fury/shaders/base.py
fury/shaders/tests/test_base.py
fury/tests/test_actors.py

This PR deprecates the function `shaders.load` in favor of the more explicit function `shaders.import_fury_shader`.

Deprecation of the function shaders.load

---

docs/examples/viz_animated_surfaces.py
docs/tutorials/01_introductory/viz_earth_animation.py
docs/tutorials/01_introductory/viz_picking.py
docs/tutorials/03_shaders/viz_principled_spheres.py
fury/actor.py

Replaced deprecated method 'label' with 'vector_text'.
Also eliminated the "true division" runtime warning.

Replaced a deprecated method.

---

docs/tutorials/01_introductory/viz_timers.py
fury/window.py

There was no way to get the id of a timer to destroy it. So I altered the "add_timer_callback" method to return the timer id so that we can use it to destroy the timer.
Also updated the tutorial viz_timers.py to show how to create/destroy timers during runtime.

Timer id is returned after creating the timer.

---

fury/tests/test_utils.py
fury/utils.py

Added a simple check to avoid the np.stack if an array is empty.
The diff looks weird, but it's simply a new if to avoid the coloring part if there is no streamlines

Support empty ArraySequence in saving (for empty vtk)

---

fury/data/__init__.py
fury/data/fetcher.py
fury/data/tests/test_fetcher.py

This PR allows us to fetch and save glTF models directly from [Khronos gltf-samples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) repository.
Demo:
```py
from fury.data import fetch_viz_gltf, read_viz_gltf
fetch_viz_gltf(['BoxTextured', 'Fox'])
fname = read_viz_gltf('Fox')
print(fname)
```

Added support for fetching gltf samples

---

docs/source/posts/2022/2022-06-08-week-1-praneeth.rst

Adding the blog post for the first week.
I have successfully generated the docs and here's the result

Adding Week1 Blog Post

---

docs/examples/physics_using_pybullet/viz_brick_wall.py
docs/examples/physics_using_pybullet/viz_chain.py
docs/examples/physics_using_pybullet/viz_domino.py
docs/examples/physics_using_pybullet/viz_wrecking_ball.py
docs/experimental/viz_brick_wall.py
fury/tests/test_window.py
fury/ui/tests/test_elements_callback.py
fury/window.py

Since it basically depends on the time needed to render a single frame using the VTK' method "**GetLastRenderTimeInSeconds()**", it will be accurate with both of the two conditions below are true:
1.  If the scene is all about rendering and no side calculations.
2. The render method is called with an offset (delay) less than (not guaranteed) or equals the time required to render a single frame.
**For example**:
If the render method is called 32 times every second, this should give a 32 FPS as calculated by [Fraps](https://fraps.com/download.php) in yellow. This makes sense since it only depends on the render time.
```
showm.add_timer_callback(True, 1000//32 , timer_callback)
```
The proposed way is to actually measure the time from rendering a frame until it renders the next frame.
For a …

Added an accurate way to get the FPS for the showManager

---

fury/data/fetcher.py
fury/data/files/KhronosGltfSamples.json
fury/data/tests/test_fetcher.py

This PR adds a JSON file containing downloadable links of all models from [glTF samples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0). This eliminates the need for API calls.
The json is generated using [this function](https://github.com/xtanion/fury/blob/gltf-json-gen/fury/data/fetcher.py#L330).

Fixing API limits reached issue in gltf fetcher

---

fury/actor.py
fury/tests/test_actors.py
fury/tests/test_utils.py
fury/utils.py

As @filipinascimento, @guaje, and I was trying to find an approach to only apply the keyframe animation on a partial subset of the actor's primitives not all of them, we found that there is no currently implemented way to get the primitives count of a single actor.
In this PR, the primitive's count is saved inside the polydata of the actor.
This can be used to distinguish the vertices of different primitives

Added primitives count to the the Actor's polydata

---

fury/io.py
fury/tests/test_io.py
fury/window.py

Users can now specify `dpi` for `window.snapshot`.
Related to #472 
To-Do:

Add DPI support for window snapshots

---

fury/ui/elements.py
fury/ui/tests/test_elements.py

Setting the visibility of a ListBox2D from `False` to `True` after creation causes the scrollbar and unused ListBox2D items to render incorrectly.
This also fixes #418

Bugfix: Visibility issues with ListBox2D

---

docs/source/posts/2022/2022-07-13-week-6-praneeth.rst

Adding Week 6 Blogpost

---

docs/source/posts/2022/2022-07-25-week-6-mohamed.rst

Week 6 blog post

---

fury/ui/elements.py
fury/ui/tests/test_elements.py

Currently, the UI sliders throw `ZeroDivisionError` whenever the `value_range` is zero ie. min_value and max_value are the same.
Adding checks to avoid these errors and setting the handle at the start.

Fixing `ZeroDivisionError` thrown by UI sliders when the `value_range` is zero (0)

---

docs/source/posts/2022/2022-08-30-week-11-mohamed.rst

Week 11 blog post

---

fury/actor.py
fury/lib.py
fury/tests/test_actors.py

There is an issue with `vector_text` which was not following the camera because no camera was assigned for it to follow.
Not sure if this is intended for the vector text to follow the camera or should it also have a direction as well if user wants.
Below is a comparison

Fixed `vector_text` not following camera

---

docs/source/posts/2022/2022-09-7-week-12-mohamed.rst

Added blog post for week 12

---

docs/source/posts/2022/2022-08-31-week-13-praneeth.rst

Adding Week 13 Blogpost

---

docs/source/posts/2022/2022-09-28-week-14-shivam.rst

blog is visible in `blog.html`

Adding week 14 blog

---

CONTRIBUTING.rst

The original file seems to have used markdown links instead of reStructuredText links. It must have been a mistake. I have fixed the three links.

Fix links in CONTRIBUTING.rst

---

fury/gltf.py
fury/io.py
fury/shaders/tests/test_base.py
fury/tests/test_actors.py
fury/tests/test_gltf.py
fury/tests/test_material.py
fury/tests/test_transform.py
fury/window.py

Fixes #642 and the following
- `window.save_image` saves flipped image. This code snippet should save black (top) to white (bottom) gradient, but did the inverse.
```py
image = np.reshape(np.tile(np.arange(0, 256).astype(np.uint8), (256*3,1)).T, (256,256,3))
print(image)
window.save_image(image, "image.png")
```
- `window.load_image` would load flipped image of the input file.
Seems like this was due to #521 https://github.com/fury-gl/fury/pull/521/commits/ecd3408d523507da27e77f324d2c12247931fa36. I reverted this and save/load was fixed. Now `window.record` was broken due to #521 https://github.com/fury-gl/fury/pull/521/commits/0e448af7e84476cc7ad12b57484844a5423e1af4 which I had to revert.
At this point basically all the changes of #521 were reverted which flipped images on …

Fix flipped images in load, save, and snapshot

---

docs/source/ext/apigen.py
docs/source/ext/scrap.py
fury/actor.py
fury/interactor.py
fury/layout.py
fury/optpkg.py
fury/shaders/tests/test_base.py
fury/testing.py
fury/ui/tests/test_elements_callback.py
fury/window.py

In python 3, we do not need `object` keyword to define a class. this is required only for python 2. 
So this PR clean up

remove object keyword from class

---

fury/ui/elements.py

Currently, each `DrawShape` has its own individual rotation_slider which rotates the shape from the center.
This increases the dependency of `DrawShape` on `DrawPanel` which we don't want.
So moving the rotation_slider to `DrawPanel`, to keep a single rotation slider and avoid excessive memory usage.

DrawPanel Update: Moving rotation_slider from `DrawShape` to `DrawPanel`

---

fury/window.py

this PR:
- remove initialize from `ShowManager` init.  : it creates a unwanted window (render is call inside initialize)
- add initialize in `add_timer_callback` .  iren need to be initialized before adding an observer

Update initialize management

---

fury/actor.py
fury/lib.py
fury/tests/test_actors.py

Adds an option to change surface representation in streamtube from triangle strips to triangles. This makes life easy with the SelectionManager. This closes PR https://github.com/fury-gl/fury/pull/708 but I am also adding an issue to improve direct picking of triangle strip representations. See here https://github.com/fury-gl/fury/issues/757
In order to know if an actor is using triangle strips or not, you need to use something like
``actor.GetMapper().GetInput().GetStrips()``

Triangle strips 2 Triangles

---

fury/primitive.py
fury/tests/test_primitive.py

Fix the issue #770.
The cause is `directions = np.array([1, 0 ,0 ])`, which is a (3, ) 1 dimension array.
It is ok for `repeat_primitive()` to use 1d array, it will be processed to `np.ndarray` in the function.
But for VTK method, directions parameter has to be `np.ndarry(N,3)`
Issue 1 can be resolved by modify the directions to `directions = np.array([[1, 0, 0]])` as a (1,3) ndarray.
For Issue 2, I have add a condition to cover the case directions = [-1, 0, 0]
Code to reproduce:
```python
from fury import window, actor
showm = window.ShowManager(scene,size=(1024, 720), reset_camera=False)
showm.initialize()
centers = np.array([[0, 0, 0]])
directions = np.array([[1, 0 ,0 ]])
colors_primitive = np.array([1,0,0])
colors_no_primitive = …
```

add one condition in `repeat_primitive` to handle direction [-1, 0, 0], issue #770

---

docs/source/ext/apigen.py
fury/lib.py

This PR improves API generation by providing a more fine-grained control over the functions/classes to document which removes a lot of `alias` keyword
We document also the `lib` module to avoid the `alias` keyword

Remove alias keyword on documentation

---

docs/source/posts/2023/2023-06-05-week-1-joaodellagli.rst

Hello everyone, here is my week 1 blogpost.

Week 1 blogpost

---

docs/source/posts/2023/2023-06-12-week-2-tvcastillod.rst

Hello, here is the blog post for week 2.

Added blogpost week 2

---

docs/source/posts/2023/2023-06-12-joaodellagli-week-2.rst
docs/source/posts/2023/2023-06-12-week-2-joaodellagli.rst

Here is my week 2 blogpost everyone, let me know of any changes needed

Week2 Blogpost

---

docs/source/posts/2023/2023-06-17-week-3-praneeth.rst

GSoC: Adding Week3 Blogpost

---

docs/source/posts/2023/2023-06-19-week-3-tvcastillod.rst

Hello, here is the blog post for week 2.

Added blogpost week 3

---

docs/source/posts/2023/2023-06-26-week-4-joaodellagli.rst

Hello guys, here is my week 4 blogpost:

Week 4 Blogpost

---

docs/source/_templates/home.html

After the #769 PR all the demos and examples were merged into a single folder called `auto_examples`. This hampered the path that were used in Scientific Domain Section. Redirecting these links according to the update.

Updating broken links in the Scientific Domain Section

---

docs/source/posts/2023/2023-07-01-week-5-praneeth.rst

GSoC: Adding Week 5 Blogpost

---

docs/source/_static/css/util.css
docs/source/_static/vendor/display-card.css
docs/source/_static/vendor/tabs.css
docs/source/_templates/home.html

PR Details:
- This PR has new changes for the physics-simulation section on the home page.

physics-simulation done

---

fury/ui/core.py
fury/ui/elements.py
fury/ui/helpers.py
fury/ui/tests/test_containers.py
fury/ui/tests/test_core.py
fury/ui/tests/test_helpers.py

The `TextBlock2D` component in the UI system was encountering alignment and scaling issues. When resizing the `TextBlock2D`, the text scaling mode was set to "SetTextScaleModeToProp," which resulted in inconsistent alignment of the text actor and improper justification of the text with respect to the background rectangle. Additionally, the background rectangle's size was calculated only after it was added to the scene, which is not an ideal practice.
To address these issues, this PR introduces the following enhancements:
1. BoundingBox Property: A new property called "boundingbox" is implemented in the `TextBlock2D`component. This property calculates the text bounding box based on the content of the `TextBlock2D`. It ensures accurate alignment and justification of the text within the …

UI: Adding Bounding Box & Fixing Alignment issue in TextBlock2D

---

docs/source/posts/2023/2023-07-22-week-8-praneeth.rst

GSoC: Adding Week 8 Blogpost

---

fury/ui/core.py
fury/ui/tests/test_core.py

Recent PR #803 added many properties to the `TextBlock2D` for improving its functionality.
This is a continuing PR which adds getter and setters for those.
Primarily focusing on `auto_font_size` & `dynamic_bbox`.

UI: Adding getters and setters for the `TextBlock2D` properties

---

docs/source/_static/css/sponsors.css
docs/source/_templates/home.html

- This PR includes changes for citation of FURY paper

citation section added

---

docs/source/posts/2023/2023-08-12-week-11-praneeth.rst

GSoC: Adding Week 11 Blogpost

---

docs/source/posts/2023/2023-08-19-week-12-praneeth.rst

GSoC: Adding Week 12 Blogpost

---

docs/source/posts/2023/2023-08-21-week-12-joaodellagli.rst

Hello everyone, here is my week 12 blogpost!

GSoC: Week 12 Blogpost

---

fury/actors/odf_slicer.py
fury/actors/peak.py
fury/actors/tensor.py
fury/data/fetcher.py

This Pull Request corrects errors in fury/actors/odf_slicer.py, fury/actors/peak.py, fury/actors/tensor.py and fury/data/fetcher.py.
fix:  #876
The following changes have been made:
Files: fury/actors/odf_slicer.py, fury/actors/peak.py and fury/data/fetcher.py
White spaces correction
error correction: E501 line too long
File fury/actors/tensor.py:
error correction: W605 invalid escape sequence '\D'
Tests:
I've run some tests to make sure the changes haven't affected the way the code works.
Coding conventions:
I have followed PEP8 coding conventions in this Pull Request.
Acknowledgements:
I thank the project contributors for their work and time.
I hope this Pull Request will be useful and that it will be integrated into the project.
Please don't hesitate to ask me questions if you need …

Fixed Pycodestyle errors in fury/actors/odf_slicer.py, fury/actors/peak.py, fury/actors/tensor.py, and fury/data/fetcher.py

---

docs/source/installation.rst

Add a coding style section to the documentation to reflect the use of the `pre-commit` and `ruff`-based style enforcement framework.

DOC: Document the coding style enforcement framework

---

fury/gltf.py
fury/tests/test_stream.py

Typo fixes in `fury/gltf.py` and `fury/tests/test_stream.py`.
`codespell` was flagging them while making GSoC blogs.
This CI in `codespell` is flagging a typo which I've fixed inside #890

[TYPO] Typo fix in code

---

docs/source/posts/2024/2024-05-28-first-post-wachiou-bouraima.rst

Changes:
-------------
-    Added  **/docs/source/posts/2024** directory for the GSoC'24 blogs. 
-    Added my first GSoC'24 blog post

DOC: Add Wachiou BOURAIMA GSoC'24 first  Blog post

---

docs/source/posts/2024/2024-06-06-week-1-robin.rst

[DOC] week 1 blog GSoC

---

docs/source/posts/2024/2024-06-15-week2-wachiou-bouraima.rst

DOC:  Add wachiou's week 2 blog post

---

.github/workflows/test.yml

Python 3.8 is deprecated so removing this CI and adding 3.12

CI: remove 3.8 add 3.12

---

fury/actor.py
fury/actors/odf_slicer.py
fury/actors/peak.py

- apply warn_on_args_to_kwargs to the module actors
- update the unittest

RF: Add keyword arguments to module: actors

---

fury/data/fetcher.py
fury/data/tests/test_fetcher.py
fury/tests/test_gltf.py

- apply warn_on_args_to_kwargs to the module data
- update the unitest

RF: Add keyword arguments to module: data

---

fury/animation/animation.py
fury/animation/helpers.py
fury/animation/tests/test_animation.py
fury/animation/tests/test_timeline.py
fury/animation/timeline.py
fury/tests/test_gltf.py
fury/tests/test_window.py

- apply warn_on_args_to_kwargs to the module animation
- update the unitest

RF: Add keyword arguments to module: animation

---

fury/ui/containers.py
fury/ui/core.py
fury/ui/elements.py
fury/ui/tests/test_core.py

- apply warn_on_args_to_kwargs to the module (UI)
- update the unitest

RF: Add keyword arguments decorator to module: UI

---

fury/deprecator.py

This PR corrects a problem related to the use of `setuptools.extern.packaging`, which is not standard and not recommended by setuptools. The problem occurs with versions of setuptools >= 71.0.3, causing an ImportError when deprecated components are called.
- Replacement of `setuptools.extern.packaging` by direct import of `packaging` into `deprecator.py`.
The `setuptools.extern` module was removed in `>=71.0.0` versions of setuptools, causing import errors. By updating the import declaration to use `packaging`, we ensure that FURY remains compatible.
- Run all existing tests to ensure no regression.
- Checked depreciation warning and error handling logic.
Fix issue #912

Fix: Replace setuptools.extern.packaging with direct packaging import

---

fury/stream/__init__.pyi
fury/stream/server/__init__.py
fury/stream/server/__init__.pyi

Implementation of lazy loading for the `fury.stream.server module`.
FIX: #917

NF: Implementation of lazy_loading in `fury.stream.server`

---

.mailmap
AUTHORS.rst
CONTRIBUTING.rst
docs/source/posts/2024/2024-07-31-release-announcement.rst
docs/source/release-history.rst
docs/source/release_notes/releasev0.11.0.rst
fury/actor.py
fury/animation/animation.py
fury/animation/interpolator.py
fury/colormap.py
fury/decorators.py
fury/optpkg.py
fury/transform.py
fury/utils.py
fury/window.py

Preparation for 0.11.0 release, targeting, July 31rst, 2024. 
March.

Release 0.11.0 Preparation 

---

docs/source/conf.py
docs/source/ext/apigen.py
fury/actors/peak.py
fury/actors/tensor.py
fury/colormap.py
fury/gltf.py
fury/lib.py
requirements/docs.txt

This PR fixes the formatting warnings in several functions across different modules:
- `actors`
- `colormap`
, specifically addressing the "Explicit markup ends without a blank line; unexpected unindent" issue in their docstrings. Additionally, the `apigen.py`  file has been refactored to fix warnings.

[DOCS][FIX][RF] fix docstring formatting warning  and refactor the apigen.py

---

docs/source/posts/2023/2023-01-29-final-report-shivam.rst

this link is broken https://fury.gl/latest/blog/author/Shivam-Anand.html
it supposed to https://fury.gl/latest/blog/author/shivam-anand.html

[FIX][DOC] fix broken link in Shivam's GSoC final report blog post

---

.github/workflows/doc.yml

Consider warnings as errors in documentation CI build.

NF: Consider warnings as errors in documentation CI build

---

docs/examples/viz_gltf.py
docs/examples/viz_gltf_animated.py
docs/examples/viz_gltf_export.py
docs/examples/viz_morphing.py
docs/examples/viz_skinning.py

Worked on a UserWarning by making sure all inputs to fetch_gltf were keyword arguments and changing those that were not.
fixes #937

Solved the fetch_gltf argument errors.

---

pyproject.toml

The new VTK have a lot of changes that make it incompatible with fury for now.
I do not think we will work on this since we are working on fury v2 which does not use VTK. 
So pinning VTK version to vtk<9.4.0

CI:  pin vtk<9.4.0

---

fury/actor.py
fury/geometry.py
fury/material.py
fury/tests/test_actor.py
fury/tests/test_geometry.py
fury/tests/test_material.py
fury/utils.py

NF: Sphere, Geometry & Material

---

fury/actor.py
fury/io.py
fury/material.py
fury/shader.py
fury/tests/test_material.py
fury/tests/test_shader.py
fury/wgsl/mesh.wgsl

- Added a slightly modified version of `Pygfx` mesh shader `mesh.wgsl` that calculates the normal on the fly and this is the starting point for billboards.
- for any `actor` user can choose to make it `smooth` or not which is a simple argument to choose between `smooth_shading` & `flat_shading` and yet in the material it make sense to use `flat_shading` since it's more commonly used for materials.

NF: shaders and materials modifiable & added smooth/flat shading

---

fury/actor.py
fury/tests/test_actor.py

added actor for cylinder

---

fury/actor.py

This PR adds a new function named `actor_from_primitive` to refactor the actors and avoid code duplication as discussed with @m-agour.
It will also make it easier to add new ones. and focus on more complex actor

NF: actor_from_primitive

---

fury/wgsl/mesh.wgsl
requirements/default.txt

A fix for the `mesh.wgsl` shader file producing error every new update of `pygfx` this will hold for a couple of future versions until the new versions of Python doesn't support `pygfx 0.9.0` anymore! Or until we find another more efficient way to do it.

fix: shader compatibility issue temp fix.

---

fury/actor.py
fury/geometry.py
fury/lib.py
fury/material.py
fury/tests/test_actor.py
fury/tests/test_geometry.py
fury/tests/test_material.py

Hello.
Added the point actor with required geometry, material and test cases.
Thank you

NF: Adding point actor and all its requirements.

---

fury/lib.py

- The name was copied from the pip show list and had `jupyter-rfb`.
- While using it with optional_package the `jupyter_rfb works as how they register the base name with python.`

BF: Fixed package name for jupyter_rfb

---

fury/__init__.py

Cleaned up deprecated VTK-related warnings controls from init file. Used built-in warnings module.

BF: remove legacy VTK warning handling

---

fury/actor.py
fury/lib.py
fury/material.py
fury/shader.py
fury/wgsl/vector_field_compute.wgsl
fury/wgsl/vector_field_render.wgsl
fury/wgsl/vector_field_thin_render.wgsl

- Introduces new shaders for thick lines and arrows.
- Fixes vector field and slicer cross-section issues.
Code to try:
```
from fury import actor, window
x, y, z = np.mgrid[0:1:20j, 0:1:20j, 0:1:20j]
u = np.sin(np.pi * x) * np.cos(np.pi * z)
v = -2 * np.sin(np.pi * y) * np.cos(2 * np.pi * x)
w = np.cos(np.pi * x) * np.sin(np.pi * z) + np.cos(np.pi * y) * np.sin(2 * np.pi * z)
vector_field = np.stack((u, v, w), axis=-1)
print(vector_field.shape)
vector_field_actor = actor.vector_field_slicer(
vector_field,
actor_type="arrow",
thickness=10.0,
scales=0.3,
visibility=(False, False, True),
)
def handle_key_event(event):
print("Key pressed:", event.key)
position = vector_field_actor.cross_section
if event.key == "ArrowUp":
position = (position[0], position[1], position[2] + …
```

NF: VectorField with arrows and thick lines
