fury/colormap.py, fury/tests/test_colormap.py, fury/tests/test_decorators.py, fury/tests/test_optpkg.py
This PR fix #8 and add tests to:
- colormap module
- decorator module
- optional package module
=> Tests addition

fury/actor.py, fury/tests/test_actors.py
Modification made in the surface function. It used to crash while adding colors for an unordered array of vertices. Fixed the bug.
=> new surface function

docs/source/_templates/versions.html, docs/source/ext/github.py, docs/source/ext/github_tools.py
- Update Root Path for doc selection
- Improve management of `try...except....` for fetching info
=> [Fix] Update doc management

.travis.yml, ci/travis/install.sh, fury/tests/test_actors.py, fury/tests/test_interactor.py, fury/tests/test_ui.py, fury/tests/test_utils.py, fury/tests/test_window.py, fury/ui.py
Trying to add headless support for OSx on Travis
This should fix #18
=> Update OSX bots on Travis

fury/tests/test_window.py
=> TEST: updated order transparency issue for vtk 8.2.0

fury/tests/test_ui.py, fury/ui.py
Add middle button callback on `UI` interface.
=> Add middle button callback

fury/actor.py, fury/tests/test_actors.py, fury/ui.py
This is not really a slicer 4D (only branch name) it is just corrections on the existing slicer.
=> Updates and corrections in slicer and ui

fury/colormap.py, fury/tests/test_colormap.py
A quick PR to update the colormap when we do not have `Matplotlib`  installed
=> [Fix] cmap when not have matplotlib

fury/io.py, fury/tests/test_io.py, fury/tests/test_window.py, fury/window.py
the goal of this PR is to fix #13.  We can now save a screenshot bigger than our screen resolution
=> [Fix] resolution limit

docs/examples/viz_roi_contour.py, docs/source/_templates/page.html, docs/source/community.rst, docs/source/conf.py, docs/source/getting_started.rst, docs/source/index.rst, docs/source/installation.rst
Quick update of installation instruction and community page
fix #36
=> [Doc] add installation instruction

.mailmap, AUTHORS.rst, CONTRIBUTING.rst, docs/source/release-history.rst, docs/source/release_notes/release0.3.0.rst, docs/source/release_notes/releasev0.3.0.rst, fury/colormap.py, fury/tests/test_actors.py, fury/tests/test_colormap.py, fury/tests/test_window.py, fury/utils.py, fury/window.py
Preparation for 0.3.0 release, targeting Thursday, August 1rst. 
October.
=> Release 0.3.0 preparation

ci/travis/install.sh
=> [miniconda] move to https

.travis.yml, ci/travis/deploy_docs.sh, ci/travis/install.sh, ci/travis/script.sh, docs/examples/viz_roi_contour.py, fury/colormap.py, fury/decorators.py, fury/tests/test_actors.py, fury/tests/test_colormap.py, fury/tests/test_window.py
Currently, we are only using Anaconda.  The goal of this PR is to add `pip` management
=> [Fix] update travis to manage pip

fury/ui.py, fury/window.py
Should fix https://github.com/fury-gl/fury/issues/96
And destroy timers if there.
=> Bug fix for double slider

fury/tests/test_ui.py, fury/tests/test_window.py
To get a more explicit error message, update `assert` to `assert_equal`
=> from assert to npt_assert_equal

docs/source/ext/github_tools.py, fury/actor.py, fury/data/fetcher.py, fury/optpkg.py, fury/tests/test_actors.py, fury/tests/test_optpkg.py, fury/tests/test_ui.py, fury/ui.py
This PR just adds some more global tests and fix some pep8.
=> Increase coverage for test_actors

fury/actor.py, fury/primitive.py, fury/tests/test_actors.py, fury/tests/test_primitive.py
Add basic primitive. The goal will be to replace glyph in the near future
=> Add basic primitives

azure-pipelines.yml, fury/tests/test_window.py, fury/window.py
use `deprecate_with_version` decorator for all deprecated function
=> Update Deprecated function

fury/actor.py, fury/io.py, fury/tests/test_io.py, fury/utils.py
changed the if case for loading poly data, added vtp (XML vtk), 
changed the coloring default name from None to RGB
MNI obj is now detected if cannot read it as OBJ
to save MNI obj you need to use ".mni.obj" extension (safer for other tools)
=> update loading and saving IO for polydata

fury/window.py
This parameter will allow different event types. Currently, the only supported event is ModifiedEvent.
=> Add event parameter on add_window_callback method in ShowManager class.

docs/tutorials/viz_spiky.py
Created new tutorial to show how to use tools from primitive and add arrows to show the normals of a sphere. Enjoy! And thank you for the great job building FURY!
=> Started new tutorial about using normals to make spiky spheres

docs/examples/viz_network.py, fury/data/__init__.py, fury/data/fetcher.py
Adding a Tutorial based on Filipi work as you can see [here](https://www.youtube.com/watch?v=ipjTMy-RrvU)
A fetcher has been added too
=> [DOC] Add demo for showing an network 

fury/convert.py, fury/primitive.py, fury/window.py
This PR is a quick fix (indentation) for documentation generation.
=> [Fix] some docstring for doc generation

fury/data/fetcher.py
This commit aims to resolve issue #121 by replacing md5 with sha256
=> updated fetcher.py

fury/ui.py
Updated/ Corrected the comments part under Disk2D class.
=> Corrected Disk2D comments

fury/window.py
Corrected spelling error in window.py
=> Spelling error 

fury/actor.py
In the example given in comments for cube actor - changed cubeactor to cube_actor
=> Documentation

docs/examples/viz_network_animated.py, requirements/docs.txt
This is a work in progress demo for animated network visualization.
Two modes are implemented, one in which the positions of nodes are defined by a force-directed layout algorithm; and another with the positions of the network being progressively displaced by random increments.
=> Animated Network Visualization Example

fury/io.py, fury/tests/test_io.py, fury/window.py
This PR fix #160. VTK seems to flip images so the code has been made more consistent to follow `pillow` rules
=> [Fix] Flipping during save

fury/tests/test_ui.py, fury/ui.py
Referencing issue #175 , my objective is to add vertical layout for LineDoubleSlider2D.
* Applied changes to the physical properties(**track**) of the slider to appear vertical.
* Added a new parameter `orientation` to determine the layout using `horizontal` or `vertical` as arguments.
* Added movement of sliders in the vertical direction.
* Add unit test for Vertical Double Slider.
* Update viz_ui.py example.
=> Vertical Layout for LineDoubleSlider2D

fury/io.py
The goal of this PR is to fix the icons flipping. it should fix #199.
=> [FIX] icons flipping

docs/tutorials/01_ui/viz_ui_slider.py, fury/tests/test_ui.py, fury/ui.py
This is a follow of @MarcCote comments as you can see [here](https://github.com/fury-gl/fury/pull/190#discussion_r393198045).
Thank you for the feedback! Can you merge this PR when CI's are done and if you do not see anything else.
Thank you
=> [FIX] avoid in-place replacements

fury/window.py
With this feature, users will now be able to remove more than one actors from the scene in one command
=> Remove more than one actors at once

fury/tests/test_ui.py, fury/ui.py, fury/window.py
This is the new PR, a fix for issue #76 as per discussion.
=> Changed options attribute from list to dict and updated respective tests

fury/primitive.py, fury/tests/test_utils.py, fury/utils.py
This PR fix #137 concerning the winding issue and the displacement. All sphere normals are correct now
=> [Fix] sphere winding issue 

MANIFEST.in, setup.py
It seems that some static files were not included during the packaging.
This PR update the directive for including them.
=> Improve packaging

docs/source/conf.py
small PR to update copyright year
=> update copyright years

azure-pipelines.yml
It seems we have an SSL certificate issue on Azure Windows.
Let's see if everything is going well when we check and force the installation (Stanford ssl certificate)
=> Install ssl certificate for azure pipeline windows

README.rst
=> Updated Step 3 in README.rst

fury/tests/test_window.py
This is in response to https://github.com/fury-gl/fury/issues/254
=> Updating test of order_transparency for compatibility with vtk 9

docs/tutorials/01_introductory/viz_solar_system.py, fury/data/fetcher.py
This PR features a new tutorial on how to create a scene with multiple actors in motion, which in this case are the planets in our solar system orbiting the sun. The tutorial shows how to calculate the orbital position of each planet relative to their gravity, which is a good example of using equations to update the position of an object. It also shows how to map the orbit of each planet into a visual path using ``actor.dots``.
=> Solar System Tutorial

docs/tutorials/02_ui/viz_combobox.py
PR for adding ComboBox UI tutorial.
Kindly merge #240 before merging this PR.
Thank You.
=> ComboBox UI tutorial

docs/source/posts/2020/2020-05-30-week-1-soham.rst, docs/source/posts/2020/2020-06-07-week-2-soham.rst, docs/source/posts/2020/2020-06-14-week-3-soham.rst, docs/source/posts/2020/2020-06-21-week-4-soham.rst, docs/source/posts/2020/2020-06-28-week-5-soham.rst, docs/source/posts/2020/2020-07-05-week-6-soham.rst, docs/source/posts/2020/2020-07-12-week-7-soham.rst, docs/source/posts/2020/2020-07-19-week-8-soham.rst, docs/source/posts/2020/2020-07-26-week-9-soham.rst, docs/source/posts/2020/2020-08-02-week-10-soham.rst
My GSoC blogs till 19th July 2020 or 8th week.
=> Python GSoC Blogs upto 19th July 2020

fury/tests/test_deprecator.py, fury/tests/test_window.py
Quick PR to fix the failing tests
=> Update Deprecated test

docs/source/posts/2020/2020-05-30-week-1-lenix.rst, docs/source/posts/2020/2020-06-07-week-2-lenix.rst, docs/source/posts/2020/2020-06-14-week-3-lenix.rst, docs/source/posts/2020/2020-06-21-week-4-lenix.rst, docs/source/posts/2020/2020-06-28-week-5-lenix.rst, docs/source/posts/2020/2020-07-05-week-6-lenix.rst, docs/source/posts/2020/2020-07-13-week-7-lenix.rst, docs/source/posts/2020/2020-07-20-week-8-lenix.rst, docs/source/posts/2020/2020-07-27-week-9-lenix.rst, docs/source/posts/2020/2020-08-02-week-10-lenix.rst
All GSoC weekly blogs till week 8
=> Python GSoC Weekly blogs 

docs/tutorials/01_introductory/viz_solar_system.py
This pull request contains a small change to the recent ``viz_solar_system.py`` tutorial. The size of the sun actor is decreased to half its original size.
=> Decreasing the size of the sun in solarsystem tutorial

.codecov.yml, docs/tutorials/04_shaders/viz_shader.py, fury/actor.py, fury/shaders/__init__.py, fury/shaders/base.py, fury/shaders/billboard_dec.frag, fury/shaders/billboard_dec.vert, fury/shaders/billboard_impl.vert, fury/shaders/tests/test_base.py, fury/tests/test_actors.py
Beginning of adding utility functions to standardize and help the shader management. Still some work to do:
Feel free to comment and add more ideas. 
fix #260
=> Shader manager

fury/io.py
Found a typo in the vtp reader function initialization, which was set to `vtkXMLPolyDataWriter`. Changed to `vtkXMLPolyDataReader`. After fix vtp loading works
=> FIX vtp reader

fury/actor.py, fury/shaders/billboard_dec.frag, fury/shaders/billboard_dec.vert, fury/shaders/billboard_impl.frag, fury/shaders/billboard_impl.vert, fury/tests/test_actors.py
This PR fixes:
- Scaling issue on the billboard actor.
- Translating issue on the billboard and SDF actors after upgrading to VTK 9.0.1.
|Updated Billboard actor |Updated SDF actor |
|---|---|
|<img width="350" alt="Issue1" src="https://user-images.githubusercontent.com/9929496/93150002-00775700-f6c6-11ea-8b48-4674db3c71ed.png">|<img width="350" alt="Issue2" src="https://user-images.githubusercontent.com/9929496/93150068-2a307e00-f6c6-11ea-9a7b-979a7bd5cfb9.png">|
=> Fixed translating and scaling issues on billboard and SDF actors

.travis.yml, docs/examples/physics_using_pybullet/viz_brick_wall.py, docs/source/posts/2020/2020-07-05-week-6-soham.rst, docs/source/posts/2020/2020-08-24-final-work-lenix.rst, docs/source/posts/2020/2020-08-24-week-13-lenix.rst, docs/tutorials/01_introductory/viz_earth_coordinates.py, fury/deprecator.py
- Removing python3.5 from Travis
- Adding python3.8 To Travis
- Fix doc generation warning
=> Remove python35 from Travis

docs/source/posts/2020/2020-08-09-week-11-soham.rst, docs/source/posts/2020/2020-08-16-week-12-soham.rst, docs/source/posts/2020/2020-08-23-week-13-soham.rst, docs/source/posts/2020/2020-08-24-final-work-soham.rst
PR to add blogs written during third evaluation.
=> GSoC blogs for Third Evaluation.

docs/examples/physics_using_pybullet/viz_domino.py
=> Added Domino-Simulation-file for Review

docs/tutorials/02_ui/viz_buttons.py, docs/tutorials/02_ui/viz_check_boxes.py, docs/tutorials/02_ui/viz_combobox.py, docs/tutorials/02_ui/viz_radio_buttons.py, docs/tutorials/02_ui/viz_shapes.py, docs/tutorials/02_ui/viz_tab.py, docs/tutorials/02_ui/viz_ui.py, docs/tutorials/02_ui/viz_ui_listbox.py, docs/tutorials/02_ui/viz_ui_slider.py
Updating all UI tutorials to the latest FURY API.
=> Update UI tutorials.

fury/shaders/billboard_dec.frag, fury/shaders/billboard_dec.vert, fury/shaders/billboard_impl.vert
This simple PR forwards the content of the variable center from the vertex shader to the fragment shader.
=> Added center forwarding in billboard shaders.

docs/source/getting_started.rst
Changed  "modelsuzanne" to "suzanne" in docs (getting started)
=> modelsuzanne to suzanne

docs/source/installation.rst
Hi Opensource team,
As the discussion goes on discord group, I had made PR for it where I removed $ in order to execute commands on the terminal. 
Regards, 
Aju Tamang
=> fix: Minor docs changes

docs/source/fury-pybullet.rst, docs/source/index.rst
=> Adding physics engine integration docs

fury/actor.py
closes #372 
Added ellipsoid as a primitive option in the comment section of sdf actor.
=> Updated actor.py

docs/tutorials/03_shaders/viz_shader.py
Minor documentation fix. Changed [VKT](https://fury.gl/latest/auto_tutorials/04_shaders/viz_shader.html#codecell2:~:text=VKT) to VTK.
=> Minor documentation fix

docs/tutorials/03_shaders/viz_sdfactor.py, fury/actor.py, fury/shaders/sdf_dec.frag, fury/tests/test_actors.py
Hi all, I noticed that fury lacked a primitive to render a capsule actor and have taken up the liberty to add an sdf for the same.
I took this up as an opportunity to expand the role of sdf's in the fury codebase. 
I have also modified the existing tests and example tutorial to include the capsule actor. 
This the final result.
All of the sdf based actors in fury so far
100 capsules rendered to check overall performance 
I humbly request the maintainers to consider adding this new actor to the vast fury codebase.
Any feedback and suggestions are most welcome.
Thank You.
=> Added an sdf for rendering a Capsule actor

.mailmap, AUTHORS.rst, LICENSE, ci/travis/script.sh, docs/examples/viz_brownian_motion.py, docs/examples/viz_helical_motion.py, docs/source/ext/github_tools.py, docs/source/posts/2021/2021-03-09-gsoc.rst, docs/source/posts/2021/2021-03-13-release-announcement.rst, docs/source/release-history.rst, docs/source/release_notes/releasev0.7.0.rst, fury/tests/test_actors.py, fury/tests/test_material.py, requirements/test.txt
Preparation for 0.7.0 release, targeting Saturday, March 13th. 
October.
=> Release 0.7.0 preparation

fury/actor.py, fury/primitive.py, fury/tests/test_actors.py, fury/tests/test_primitive.py
I made a primitive for triangular prism and created an actor for the same. Added tests for actor and primitive too. 
Preview -
=> added primitive and actor for triangular prism, added tests too

paper.bib, paper.md
Quick PR to add doi on the paper
=> fix paper doi

paper.md
=> update sk orcid

CONTRIBUTING.rst, ci/windows/install_opengl.ps1, docs/source/ext/github_tools.py, fury/material.py, fury/tests/test_actors.py, fury/tests/test_material.py
Quick PR to fix the failing CI's on Windows. Opengl was not found anymore
=> [Fix] Update Azure pipeline for windows

fury/actor.py, fury/window.py
This PR is just for cleaning purposes. I removed the old deprecated functions/classes
=> Remove deprecated functions

paper.bib
This PR addresses an issue in the bibtex of the JOSS paper.
=> Fixed bibtex

docs/source/introduction.rst
This PR adds a Statement of Need section to the documentation About page.
=> Updated about documentation

fury/layout.py, fury/tests/test_layout.py
This PR adds support for `HorizontalLayout` in `layout` module. Below is a screenshot for reference.
=> Added Horizontal Layout to `layout` module

.github/workflows/test.yml, azure-pipelines.yml
VTK wheels are available!!! Ths PR just adds python3.9 matrix for all our CI's. 
For more information, see:
- https://discourse.vtk.org/t/vtk-python-3-9-wheels/5049/7
- https://pypi.org/project/vtk/9.0.20210612.dev0/
=> Add python3.9 for our CI's

fury/io.py, fury/tests/test_io.py
This PR adds the functionality to process/load sprite sheets.
=> Method to process and load sprite sheets

fury/__init__.py, fury/actor.py, fury/actors/odf_slicer.py, fury/actors/peak.py, fury/actors/tests/test_peak.py, fury/colormap.py, fury/convert.py, fury/interactor.py, fury/io.py, fury/lib.py, fury/material.py, fury/pick.py, fury/primitive.py, fury/shaders/base.py, fury/shaders/tests/test_base.py, fury/testing.py, fury/tests/test_actors.py, fury/tests/test_interactor.py, fury/tests/test_io.py, fury/tests/test_material.py, fury/tests/test_shaders.py, fury/tests/test_testing.py, fury/tests/test_utils.py, fury/ui/containers.py, fury/ui/core.py, fury/utils.py, fury/window.py
This PR is the beginning of #457. 
The goal is to make our scripts load faster by importing only the functions/modules we need from VTK.
=> Update the way we import external libraries by using only the necessary modules

docs/examples/physics_using_pybullet/viz_ball_collide.py, docs/examples/physics_using_pybullet/viz_brick_wall.py, docs/examples/viz_network.py, docs/examples/viz_network_animated.py, docs/tutorials/01_introductory/viz_earth_animation.py, docs/tutorials/01_introductory/viz_selection.py, docs/tutorials/01_introductory/viz_surfaces.py, docs/tutorials/01_introductory/viz_texture.py
This PR is a follow-up of #457 and #504. 
We are now using `fury.lib` in all examples.
=> update tutorial import

.github/workflows/test.yml
Fix mesa installation on Ubuntu 20.04
=> [FIX] Mesa installation

fury/actor.py, fury/shaders/tests/test_base.py, fury/tests/test_actors.py, fury/tests/test_interactor.py, fury/tests/test_material.py, fury/tests/test_pick.py, fury/tests/test_utils.py, fury/tests/test_window.py, fury/ui/tests/test_containers.py, fury/ui/tests/test_core.py, fury/ui/tests/test_elements.py, fury/window.py, test_platform.sh
This PR aims to resolve multiple issues:
a) The circular import issue with DIPY. See also https://github.com/dipy/dipy/pull/2493
b) Fixing the bad window issues we get from time to time during testing.
c) Solves an issue with windows staying open and not closing as fast as they should during tests.
d) Finally, this PR is also dealing with a segmentation fault issue that pytest has when running multiple files at once.
For more information see here https://github.com/pytest-dev/pytest/issues/3672
Our current solution for the later is to run pytest on individual files. Pytest claims that this is an issue with software opening threads but this is to be seen.
=> Changing how we do things with our test suite.

.github/workflows/test.yml, README.md
This PR goal is to provide an option to interact with the GH Virtual Machine.
=> [WIP] Add debugging CI Tools

README.md, fury/actor.py, fury/ui/containers.py, fury/ui/core.py
This PR just clean up the actor module to follow the current convention.
=> Remove and replace vtkactor from docstring

fury/shaders/base.py
This PR adds missing shader blocks.
=> [ENH] Add missing shaders block

.mailmap, AUTHORS.rst, LICENSE, docs/examples/viz_pbr_interactive.py, docs/examples/viz_play_video.py, docs/source/posts/2022/2022-01-31-release-announcement.rst, docs/source/release-history.rst, docs/source/release_notes/releasev0.8.0.rst, docs/tutorials/03_shaders/viz_pbr_spheres.py, docs/tutorials/03_shaders/viz_principled_spheres.py, fury/actor.py
Preparation for 0.8.0 release, targeting, January 31rst. 
March.
=> Release preparation 0.8.0

.github/workflows/test.yml, azure-pipelines.yml
The goal of this PR is to add some OpenGL flags to improve the offline rendering.  
See [here](https://docs.mesa3d.org/envvars.html) for more OpenGL flags
and [here](https://discourse.vtk.org/t/how-can-i-display-the-vtk-3d-volume-rendering-results-onscreen-in-a-remote-connection-with-workstation-x11/6356/4?u=skoudoro) for the advice / discussion
=> Add OpenGL flags for offscreen rendering

docs/examples/viz_fractals.py
Added a new example/demo with three fractals. These are built using `repeat_sources`.
https://user-images.githubusercontent.com/72246047/162490498-148dad0b-a852-48ea-84ba-775a194c187f.mp4
=> Add new example/demo: three-dimensional fractals

fury/layout.py, fury/tests/test_layout.py
This PR adds the functionality of `x`, `y`, `z` layouts in the layout module. Please merge #480 and #479 before reviewing/merging this.
=> Added `x,y,z` layouts to the layout module.

fury/tests/test_window.py, fury/window.py
This PR adds the `save_screenshot` function to the `ShowManager`, reusing its class attributes instead of creating a new ShowManager as in the `record` function.
=> Function to save screenshots with magnification factor

README.md
Changing the author's name from `Garyfallidis, Eleftherios,` to  `Eleftherios Garyfallidis`.
=> Updating author's name in README

fury/data/__init__.py, fury/data/fetcher.py
Creating a fetcher function to fetch the new icons required for the `DrawPanel UI`.
Demo:
```python
from fury.data import fetch_viz_new_icons
fetch_viz_new_icons()
```
=> Creating a fetcher to fetch new icons

docs/source/posts/2022/2022-06-20-week1-shivam.rst
A blog post for the first week of coding. I still need to add a few images and update this PR.
I was able to generate the docs, but the theme looks off for some reason.
=> Adding week 1 blog post

docs/source/posts/2022/2021-06-08-week-1-mohamed.rst
Update 2: It's done.
Update: This PR still needs some improvements and review from my end and will do this by today.
My blog post for the first week.
=> Added week 1 post

docs/source/posts/2022/2022-06-15-week-2-praneeth.rst
Adding week 2 blog post.
I have generated the docs and the blog is visible in the blog.html
=> Adding Week 2 Blog Post

docs/source/posts/2022/2022-06-29-week2_blog.rst
Docs are generating fine and it's visible in blogs.html
=> Added week 2 blog

docs/source/posts/2022/2022-06-22-week-3-praneeth.rst
=> Adding Week 3 BlogPost

docs/source/posts/2022/2022-06-29-week-4-praneeth.rst
Adding Weekly Blogpost for Week-4.
=> Adding Week 4 Blogpost

docs/source/posts/2022/2022-07-11-week-4-mohamed.rst
Added week 4 blog post which contains some info and a single video.
=> Added week 4 blog post

docs/source/posts/2022/2022-07-19-week-5-mohamed.rst
=> Added week 5 blog post

docs/source/posts/2022/2022-07-12-week4-shivam.rst, docs/source/posts/2022/2022-07-19-week5-shivam.rst
The blog is visible in `blos.html`
=> Adding week 5 blog post

docs/source/posts/2022/2022-07-25-week-6-shivam.rst
The blog is visible in `blogs.html`
=> Adding week 6 blog post

docs/source/posts/2022/2022-07-20-week-7-praneeth.rst
=> Adding Week 7 Blogpost

docs/source/posts/2022/2022-08-01-week-7-mohamed.rst
=> Added week 7 blog post

docs/source/posts/2022/2022-08-01-week-7-shivam.rst
blog is visible in `blogs.html`
=> Adding week 7 blog post

docs/source/posts/2022/2022-07-27-week-8-praneeth.rst
=> Adding Week 8 Blogpost

docs/source/posts/2022/2022-08-09-week-08-shivam.rst
Blog is visible in `blogs.html`
=> Adding week 8 blog post

docs/source/posts/2022/2022-08-03-week-9-praneeth.rst
=> Adding Week 9 Blogpost

docs/source/posts/2022/2022-08-16-week-9-mohamed.rst
=> Week 9 blog post

docs/source/posts/2022/2022-08-17-week-09-shivam.rst
blog is visible in `blogs.html`
=> Adding week 9 blog post

docs/source/posts/2022/2022-08-23-week-10-mohamed.rst
=> Added blog post for week 10

docs/source/posts/2022/2022-08-10-week-10-praneeth.rst
=> Adding Week 10 Blogpost

docs/source/posts/2022/2022-08-25-week-10-shivam.rst
blog is visible in `blogs.html`
=> Adding week 10 blog post

docs/source/posts/2022/2022-08-17-week-11-praneeth.rst
=> Adding Week 11 Blogpost

docs/source/posts/2022/2022-08-31-week-11-shivam.rst
=> Adding week 11 blog post

docs/source/posts/2022/2022-08-24-week-12-praneeth.rst, docs/tutorials/02_ui/viz_drawpanel.py
=> Adding Week 12 Blogpost

docs/source/posts/2022/2022-09-20-week-13-mohamed.rst
=> Added week 13 post

fury/ui/elements.py
In this PR, I introduce some improvements to the `PlaybackPanel` by allowing setting its position and width as well as making it responsive to window resizing by default.
https://user-images.githubusercontent.com/63170874/191489960-0ccb0b26-983c-4708-bf27-905afb55307c.mp4
=> Set position and width of the `PlaybackPanel`

docs/source/posts/2022/2022-09-15-week-13-blog.rst
=> Adding week 13 blog post

docs/source/posts/2022/2022-09-28-week-14-mohamed.rst
=> Added blog post for week 14

docs/source/posts/2022/2022-09-21-week-16-praneeth.rst
=> Adding Week 16 Blogpost

docs/source/posts/2022/2022-09-14-week-15-praneeth.rst
=> Adding Week 15 Blogpost

fury/tests/test_window.py, fury/window.py
This closes #603  and maybe  #578
=> Fix: segfault created by record method

docs/source/_static/vendor/gallery.css, docs/source/_static/vendor/installtext.css, docs/source/_static/vendor/style.css, docs/source/_static/vendor/styles.css, docs/source/_static/vendor/tabs.css, docs/source/_templates/home.html
* **What kind of change does this PR introduce?**
* It is a bugfix PR. It fixes all the issues related to the home page's mobile-friendliness.
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* No
* **List of fixes**:
* Main logo and description alignment issues.
* Hamburger menu alignment fixed.
* Horizontal scrolling due to overflowing elements fixed.
* Install text and command showing properly.
* Tab sections got a new mobile-friendly layout.
* Footer properly aligned and readable.
=> Home page mobile friendly

docs/source/_static/vendor/fonts.css, docs/source/_static/vendor/gallery.css, docs/source/_static/vendor/installtext.css, docs/source/_static/vendor/style.css, docs/source/_static/vendor/styles.css, docs/source/_static/vendor/tabs.css, docs/source/_templates/home.html, docs/source/conf.py
- This PR changes the logo and logo sizes and fonts according to the new design.
- This PR uses the home-page-mobile-friendly as the base PR, thus will require that PR to be merged to master first.
=> Logo changes

fury/animation/tests/test_interpolators.py, fury/tests/test_stream.py
This PR fixes some tests related to the last Numpy release. A way to be more rigorous.
=> Fix failing tests due to last numpy release

.github/workflows/doc.yml, .github/workflows/test.yml, docs/Makefile, docs/source/conf.py, docs/source/ext/github_tools.py, fury/colormap.py, fury/data/fetcher.py, fury/tests/test_colormap.py
small PR to allow update blog post and website with github action
=> Improve Doc management + quick fix

docs/source/posts/2022/2023-01-24-final-report-praneeth.rst
Adding final report for the GSoC'22.
It is also visible in the blog.html
=> Adding GSoC'22 Final Report

fury/data/fetcher.py
=> added a check for operating system before executing the tput command through popen in fury/data/fetcher.py update_progressbar() function

docs/source/posts/2023/2023-01-31-final-report-mohamed.rst, fury/animation/tests/fares
I couldn't generate the HTML for this blog post yet because of some errors. But, I'm working on it.
=> Added GSoC'22 Final Report

docs/tutorials/02_ui/viz_ui_slider.py
In viz_ui_slider.py, both horizontal and vertical sliders were connected to horizontal movement "cube.SetPosition(value, 0, 0)".
I created two functions for horizontal and vertical movements and connected them to the right sliders.
=> Connected the sliders to the right directions

docs/tutorials/01_introductory/viz_slice.py
This is the update for the deprecated function `get.data()` in the tutorial file.
ps: I don't know how to update the source file for the website..
=> update deprecated function get.data() to get.fdata()

fury/ui/elements.py
The left_mouse_button_clicked callback for the drop_down_button was inside a for loop. Fixed indentation.
=> ComboBox2D drop_down_button mouse callback was inside for loop

docs/source/getting_started.rst
update the instruction to online Getting Started page.
First PR#761 is not reflected in the file. This is the second attempt.
=> add instruction about how to get Suzanne model

fury/actor.py, fury/shaders/billboard/cylindrical_x.glsl, fury/shaders/billboard/cylindrical_y.glsl, fury/shaders/billboard/spherical.glsl, fury/shaders/billboard_dec.frag, fury/shaders/billboard_dec.vert, fury/shaders/billboard_impl.frag, fury/shaders/billboard_impl.vert, fury/shaders/utils/billboard_normalization.glsl, fury/tests/test_actors.py
The current billboard actor only supports spherical billboards functionality, this PR is intended to add the option of using cylindrical billboards.
=> Cylindrical billboard implementation

fury/ui/containers.py
this PR solves #776:
- it provides a parameter to initialize it collapsed for some applications.
- it allows to collapse/expand by single clicking on the active tab.
@guaje, can you test this branch and let me know if it is ok for you? thanks
=> TabUI collapsing/expanding improvements

requirements/docs.txt
This PR fixes the glitches in the deployment of Fury about the documents pages
=> versions-corrected

docs/source/posts/2023/2023-06-02-week-0-praneeth.rst
=> Adding Week0 Blogpost

docs/source/posts/2023/2023-06-02-week-0-tvcastillod.rst
Hello, here is my first blogpost.
=> Added blogpost week 0

docs/source/posts/2023/2023-06-11-week-2-praneeth.rst
=> Adding Week2 BlogPost

docs/source/posts/2023/2023-06-24-week-4-praneeth.rst
=> GSoC: Adding Week 4 Blogpost

docs/source/posts/2023/2023-07-08-week-6-praneeth.rst, docs/source/posts/2023/2023-07-15-week-7-praneeth.rst
=> GSoC: Adding Week 6 - 7 Blogpost

docs/source/posts/2023/2023-07-17-week-7-joaodellagli.rst
Hello everyone, here is my week 7 blogpost:
=> GSoC: Week 7 Blogpost

docs/source/posts/2023/2023-07-24-week-8-joaodellagli.rst
Hello everyone, here is my week 8 blogpost:
=> GSoC: Week 8 Blogpost

docs/source/posts/2023/2023-08-07-week-10-joaodellagli.rst
Hello everyone, here is my week 10 blogpost:
=> GSoC: Week 10 Blogpost

docs/source/posts/2023/2023-07-29-week-9-praneeth.rst
=> GSoC: Adding Week 9 Blogpost

docs/source/posts/2023/2023-07-25-week-8-tvcastillod.rst, docs/source/posts/2023/2023-07-31-week-9-tvcastillod.rst, docs/source/posts/2023/2023-08-08-week-10-tvcastillod.rst, docs/source/posts/2023/2023-08-16-week-11-tvcastillod.rst
Hi, here are the blog post for weeks 8, 9, 10, and 11.
=> Added blogposts week 8, 9, 10, 11

docs/source/posts/2023/2023-08-05-week-10-praneeth.rst
=> GSoC: Adding Week 10 Blogpost

docs/source/posts/2023/2023-08-25-final-report-praneeth.rst
Gist Link for more accessibility: https://gist.github.com/ganimtron-10/af9f058fffeaebbba7ff4844f712b721
=> GSoC: Adding Final Report 23

docs/source/_static/css/custom.css, docs/source/_static/css/navbar.css, docs/source/_static/vendor/styles.css, docs/source/_static/vendor/vars.css, docs/source/_templates/custom-title.html, docs/source/conf.py, requirements/docs.txt
- This pull request introduces two main enhancements to the project. Firstly, it implements a Dark mode feature, allowing users to switch between light and dark themes for improved readability and reduced eye strain in low-light environments. Secondly, it addresses an issue with the search bar functionality, the search icon being non-functional and the shortcut accessibility also being non-functional. These changes aim to enhance the user experience by providing a more versatile interface and ensuring smoother navigation and interaction within the application.
- No Related Issues
* Updated Python-sphinx-theme from 0.12.0 to 0.15.2(Stable)
* Implemented Dark mode feature.
* Fixed issues related to the search bar functionality. (Search Icon in Navbar, and shortcut not functional)
* Added …
=> Added Dark mode, Fixed Search Bar for documentation site

docs/source/posts/2024/2024-07-06-week5-wachiou-bouraima.rst
=> DOC: add Wachiou's week5 Blog post

fury/shaders/base.py, fury/shaders/tests/test_base.py
- apply warn_on_args_to_kwargs to the module (shaders)
- update the unitest
=> RF: Add keyword arguments decorator to module: shaders

fury/stream/client.py, fury/stream/server/async_app.py, fury/stream/server/main.py, fury/stream/tools.py, fury/stream/widget.py, fury/tests/test_stream.py
- apply warn_on_args_to_kwargs to the module (stream)
- update the unit tests
=> RF: add keyword arguments decorator (warn_on_args_to_kwargs) in the module: stream

docs/source/posts/2024/2024-07-27-week6-robin.rst, docs/source/posts/2024/2024-07-27-week7-robin.rst, docs/source/posts/2024/2024-07-27-week8-robin.rst
GSoC Blogs Week 6, 7, 8
Preview:
| Week 6 | Week 7 | Week 8 |
|---|---|---|
| ![image](https://github.com/user-attachments/assets/3ff931c3-550b-41f4-86f1-0bf9ea7a3121) | ![image](https://github.com/user-attachments/assets/b5e35716-240e-4c74-ae48-401e64b81ab9) | ![image](https://github.com/user-attachments/assets/cebd1c34-4382-4ba2-9e30-6bd6166a1dad) |
=> DOC: GSoC Blogs Week 6, 7, 8

docs/source/posts/2024/2024-08-17-week12-wachiou.rst
=> [DOCS]: Wachiou's week12 Blog posts

docs/source/_static/vendor/styles.css
This PR fixes the footer distortion problem when displaying the home page. 
Fix #874
=> [FIX] Fix footer deformation on hover

docs/source/posts/2024/2024-08-13-week9-wachiou.rst, docs/source/posts/2024/2024-08-15-week10-wachiou.rst, docs/source/posts/2024/2024-08-15-week11-wachiou.rst
=> [DOCS]: Weeks 9, 10 and 11 Blog posts

README.md
Add documentation CI build status badge to README file.
=> DOC: Add documentation CI build status badge to README file

.github/workflows/check_format.yml, .github/workflows/codespell.yml, .github/workflows/doc.yml, .github/workflows/test.yml, pyproject.toml
- Remove vtk from pyproject.toml
- python 3.10 as a minimum
=> RF: update some settings files

fury/transform.py, fury/utils.py
Restored functionalities from `utils.py` and `transform.py` needed by `prim_actors`.
=> Adding utils.py and transform.py needed by prim_actors

.github/workflows/test.yml, ci/install_opengl.ps1, ci/run_tests.sh, ci/setup_headless.sh, fury/__init__.py, fury/animation/__init__.pyi, fury/animation/tests/test_animation.py, fury/animation/tests/test_timeline.py, fury/animation/timeline.py, fury/convert.py, fury/tests/test_actor.py, fury/tests/test_actors.py, fury/tests/test_colormap.py, fury/tests/test_gltf.py, fury/tests/test_interactor.py, fury/tests/test_layout.py, fury/tests/test_molecular.py, fury/tests/test_optpkg.py, fury/tests/test_pick.py, fury/tests/test_stream.py, fury/tests/test_testing.py, fury/tests/test_thread.py, fury/tests/test_transform.py, fury/tests/test_utils.py, fury/tests/test_window.py, fury/ui/tests/test_containers.py, fury/ui/tests/test_core.py, fury/ui/tests/test_elements.py, fury/ui/tests/test_elements_callback.py, fury/ui/tests/test_helpers.py
This PR enable the tests of the v2 branch.
To do so, many tests has been skipped for now. The goal is to enable them step by step, each time we introduce a new feature.
Now, CI's should give us a better indicator and should come all green
=> RF: Enable Test for v2 branch

ci/setup_headless.sh, fury/tests/test_actor.py
this PR just update our CI's by installing some driver. 
we should be able to use `snapshot` function now. So, some tests has been enable to check that.
supersed #961
=> RF: install wgpu and mesa driver for ubuntu CI's

fury/actor.py, fury/geometry.py, fury/tests/test_actor.py, fury/tests/test_geometry.py
Fix line triggering error when "color per whole set of lines" case
issue: #982
=> Fix `line` actor colors 

fury/actor.py, fury/tests/test_actor.py
``` python
from fury.actor import ellipsoid
from fury.window import ShowManager, Scene
from scipy.spatial.transform import Rotation as R
centers = np.array([[0, 0, 0], [7, 0, 0], [0, 7, 0]])
lengths = np.array([[3, 1.5, 1], [3, 1, 1], [2, 3, 1]])
colors = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
axes = np.array([
np.eye(3),
R.from_euler('xyz', [45, 45, 45], degrees=True).as_matrix(),
R.from_euler('xyz', [0, 90, 0], degrees=True).as_matrix()
])
actor = ellipsoid(centers, orientation_matrices=axes, lengths=lengths, colors=colors)
scene = Scene()
scene.add(actor)
show_m = ShowManager(scene=scene, title="FURY 2.0: Ellipsoid")
show_m.start()
```
=> NF: added `ellipsoid` actor 

fury/actor.py, fury/primitive.py, fury/tests/test_actor.py, fury/tests/test_primitive.py
Added disk actor and its test cases. Here is demo of disk actor:
=> NF: Adding disk actor

fury/actor.py, fury/tests/test_actor.py
- Added position argument for text actor.
- Name fix form test_flat_disk to test_disk.
=> RF: Added position argument for text actor and name fix.

docs/examples/viz_vector_field.py, fury/actor.py, fury/material.py, fury/tests/test_actor.py, fury/tests/test_material.py, fury/tests/test_shader.py, fury/wgsl/vector_field_compute.wgsl, fury/window.py
**PR Contents**
- Test cases for actor, material and shader of vector field.
- Tutorial to use vector field and vector field slicer.
- Updates for removing noise vectors.
- Update for putting the arrows in correct direction from camera.
**Testing**
- Please use the provided `viz_vector_field.py` example.
**Preview**
=> ENH: Test cases and Tutorial for VectorField

fury/actor.py, fury/geometry.py, fury/lib.py, fury/material.py, fury/tests/test_actor.py, fury/tests/test_geometry.py, fury/tests/test_material.py
Added image actor in #985 but with directions
=> NF: Image Actor w/ Directions
